version: '3.4'

services:
  synapse:
    container_name: 'synapse'
    image: 'matrixdotorg/synapse:v1.20.1'
    restart: 'unless-stopped'
    ports:
      - '18008:8008'
      - '18448:8448'
    volumes:
      - './data/:/data/'

  riot:
    container_name: 'riot'
    image: 'vectorim/riot-web:v1.7.8'
    restart: 'unless-stopped'
    ports:
      - '18010:80'
    volumes:
      - './riot-config.json:/app/config.json'
